spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      url: jdbc:mysql://127.0.0.1:3306/fdgtest
      username: root
      password: 748123
      # ?????
      initialSize: 5
      # ???????
      minIdle: 10
      # ???????
      maxActive: 20
      # ?????????????
      maxWait: 60000
      # ???????????????????????????????
      timeBetweenEvictionRunsMillis: 60000
      # ??????????????????????
      minEvictableIdleTimeMillis: 300000
      # ??????????????????????
      maxEvictableIdleTimeMillis: 900000

