fdg:
# 系统配置
  delete-old-data-flag: true
  batch-flag: true
  submit-count: 2500
  sql-values-count: 10

---
# 单表配置
fdg:
  single-table:
    table: test_1
    schema: fdgtest
    count: 100
    value-list:
      - column-name: key1
        value: 111
      - column-name: key2
        value: 111

---
# 批量处理配置
fdg:
  batch:
    group-list:
      - table-list:
          - schema-name: fdgtest
            table-name: test_1
            count: 12
          - schema-name: fdgtest
            table-name: test_2
            count: 12
        value-list:
          - schema-name: fdgtest
            table-name: test_1
            column-name: key1
            value: 111
          - schema-name: fdgtest
            table-name: test_2
            column-name: key1
            value: 111
---
# 数据库链接信息
database:
  type: MySQL
  url: jdbc:mysql://127.0.0.1:3306/fdgtest
  username: root
  password: 748123
  driver-class-name: com.mysql.cj.jdbc.Driver